---
EnableDefaultLinters: false
glob: "**/*.erb"
exclude:
  - "vendor/**/*"
  - "tmp/**/*"
  - "node_modules/**/*"

linters:
  ParserErrors:
    enabled: true
  ErbSafety:
    enabled: true
  NoUnusedDisable:
    enabled: true
