blocked_words:
  - arse
  - asshole
  - assholes
  - bastard
  - bastards
  - bitch
  - bitches
  - bullshit
  - crap
  - cunt
  - cunts
  - damn
  - dick
  - dicks
  - douche
  - douchebag
  - fuck
  - fucked
  - fucker
  - fuckers
  - fucking
  - hell
  - jackass
  - piss
  - prick
  - pricks
  - shit
  - shitty
  - slut
  - sluts
  - whore
  - whores
